### PR TITLE
Dark mode issue

### PR DESCRIPTION
**Pull request by nupur-jeswani**
Hey, solved the dark mode issue!
Could you please check out the "dark-mode-issue" branch for the same?

### CODE REVIEW

**Comment by harisdev-netizen** [comment]
Have you checked reviewed it with live server? I am currently busy in some other project so won't be able to check myself. Anyways stay connected for more open source projects.

**Review by harisdev-netizen — COMMENTED** [review]
So far the changes seems perfect. I will give a detail review after some time though. ;)

**Comment by nupur-jeswani** [comment]
> Have you checked reviewed it with live server? I am currently busy in some other project so won't be able to check myself. Anyways stay connected for more open source projects.

Yes, it seems good to me! Just wanted to confirm it.

**Comment by nupur-jeswani** [comment]
> So far the changes seems perfect. I will give a detail review after some time though. ;)

Thank you for your time!

**Comment by harisdev-netizen** [comment]
> > So far the changes seems perfect. I will give a detail review after some time though. ;)
> 
> Thank you for your time!

No problem at all.

**Pull request merged**
